### ISSUE TITLE
Saving attachments does not work

### ISSUE THREAD

**Issue by luporr** [jcs/rubywarden#118] opened 2020-06-30 21:09 UTC
When clicking the download icon to download an attachment from an entry, it begins spinning without anything happening. When selecting another and then reselecting the initial entry everything is normal again.

Rubywarden version from current master branch, Bitwarden client version 1.18.0 on macOS 10.15.5

**Comment by jcs** [comment] 2020-06-30 21:19
Duplicate of #95

**Closed by jcs** 2020-06-30 21:19 UTC
